<a href="https://colab.research.google.com/github/atharva7279/my_deeplearning/blob/main/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
my_list = [3,6,9,10]
print(my_list)

[3, 6, 9, 10]


In [ ]:
arr = np.random.rand(5,3)
arr
arr.dtype

dtype('float64')

In [ ]:
tensor_2d = torch.randn(3,4)

In [ ]:
tensor_2d

tensor([[ 0.2939, -1.3313,  0.5403, -0.3126],
        [ 1.2965, -0.6663,  0.0796,  0.2596],
        [ 0.4209, -1.4275, -0.1561, -1.7023]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# create tensor from arr
my_tensor = torch.tensor(arr)
my_tensor

tensor([[0.1451, 0.6052, 0.5029],
        [0.5338, 0.5151, 0.3577],
        [0.8430, 0.9659, 0.6425],
        [0.8648, 0.3264, 0.5556],
        [0.9111, 0.0803, 0.2133]], dtype=torch.float64)

tensor operations


In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape and view

my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# if we dont know number of item

my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(2 ,-1)

In [ ]:
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# using view
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3[1][2] = 1212
my_torch3

tensor([[   0,    1,    2,    3,    4],
        [   5,    6, 1212,    8,    9]])

In [ ]:
# slicing
my_torch4 = torch.arange(10)
my_torch4[2]

tensor(2)

In [ ]:
# grab a slice
my_torch4 = torch.arange(10).reshape(5,2)
my_torch4[1:3 , 1]

tensor([3])

math operations

In [ ]:
t1 = torch.tensor([3,4,5,6])
t1.dtype

torch.int64

In [ ]:
t2 = torch.tensor([1,1,1,1])

In [ ]:
t1+t2

tensor([4, 5, 6, 7])

In [ ]:
t2 = t2.reshape(4,1)
t1*t2

tensor([[3, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6]])

In [ ]:
t1-t2

tensor([[2, 3, 4, 5],
        [2, 3, 4, 5],
        [2, 3, 4, 5],
        [2, 3, 4, 5]])

In [ ]:
print(t1)
print(t2)

tensor([3, 4, 5, 6])
tensor([[1],
        [1],
        [1],
        [1]])


In [ ]:
t2 = t2.reshape(1,4)

In [ ]:
t1-t2

tensor([[2, 3, 4, 5]])

In [ ]:
t1%t2

tensor([[0, 0, 0, 0]])

In [ ]:
t2 = torch.tensor([2,3,4,2])
t1**t2

tensor([  9,  64, 625,  36])

In [ ]:
# reassignment
t1 = t1+t2
print(t1)

tensor([5, 7, 9, 8])


In [ ]:
t1 += t2

In [ ]:
print(t1)

tensor([ 7, 10, 13, 10])


building neural network

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Model(nn.Module):
  #input layer (4 features of flower)